"""empty message

Revision ID: 55cd3879e2af
Revises: f6e5b8864392
Create Date: 2022-06-01 11:06:06.173027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cd3879e2af'
down_revision = 'f6e5b8864392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Shows_id'), 'Shows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Shows_id'), table_name='Shows')
    op.drop_column('Shows', 'id')
    # ### end Alembic commands ###
