"""empty message

Revision ID: 5a532695ba6f
Revises: bfd3ea1ef879
Create Date: 2022-05-26 13:34:49.749355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a532695ba6f'
down_revision = 'bfd3ea1ef879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Artists_id'), 'Artists', ['id'], unique=False)
    op.add_column('Shows', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Venues_name'), 'Venues', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Venues_name'), table_name='Venues')
    op.drop_column('Shows', 'id')
    op.drop_index(op.f('ix_Artists_id'), table_name='Artists')
    # ### end Alembic commands ###
